version: '2'
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
      day: "saturday"
      time: "09:00"
      timezone: "Europe/Paris"
    allow:
      - dependency-type: "production"

  - package-ecosystem: 'gitsubmodule'
    directory: '/'
    schedule:
      interval: 'daily'
      time: "08:00"
      timezone: "Europe/Paris"
    commit-message:
      prefix: "optc-db"
