pages:
  image: node:latest
  variables:
    GIT_SUBMODULE_STRATEGY: recursive
  script:
  - npm ci
  - npm run extract-optcdb
  - npm run test
  - npm run build
  - rm -r public && mv build public
  artifacts:
    paths:
    - public
  only:
  - main
