name: CI/CD

on:
  push:
    branches:
      - master
  # pull_request:
  #   branches:
  #   - master

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true

      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'

      - name: CI
        run: |
          npm ci
          npm test
          npm run build

      - name: CD
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
