name: OPTC-DB dependency checker

on:
  push:
    branches:
      - dependabot/**
      - feature/**

jobs:
  build-test-check-db:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'npm'

      - name: Restore package & run test
        run: |
          npm ci
          npm run extract-optcdb
          npm run extract-shipdb
          npm test
