name: OPTC-DB dependency checker

on:
  push:
    branches:
      - dependabot/submodules/src/optcdb-*
      - feature/*

jobs:
  build-test-check-db:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true

      - uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: 'npm'

      - name: Restore package & run test
        run: |
          npm ci
          npm run extract-optcdb
          npm test

      - name: Extract validation errors
        uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: extract-optc-db-error
          path: |
            public/errors-old.json
            public/errors-new.json
