name: OPTC-DB dependency checker

on:
  push:
    branches:
      - dependabot/**
      - feature/**

jobs:
  build-test-check-db:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'

      - name: Restore package & run test
        run: |
          npm ci
          npm run extract-optcdb
          npm test

      - uses: actions/upload-artifact@v3
        name: Extract validation errors
        if: failure()
        with:
          name: extract-optc-db-error
          path: |
            public/errors-old.json
            public/errors-new.json
